- name: Variables from prompt
  hosts: web
  vars_prompt:
  - name: Course
    prompt: Enter the course name
    private: false
  - name: Duration
    prompt: Enter the Duration
    private: false
  - name: Mentor
    prompt: Mentor name
    private: true
  tasks:
  - name: Print the Information
    ansible.builtin.debug:
      msg: "This is {{Course}},{{Duration}}, by {{Mentor}}"