- name: Devops Course
  hosts: local
  connection: local
  vars:
    course: "AWS Devops"
    duration: 150.0
    topics:
    - Shell
    - Ansible
    - kubernetes 
    livestream: true
    tools:
       ci=Jenkins
       cm=Ansible
  tasks:
  - name: Print information in detail
    ansible.builtin.debug:
      msg:  "This is {{course}} with total duration of {{duration}} and topics covering are {{topics}} with livestream {{livestream}} includes {{tools}} also"
  