- name: Installation package
  hosts: web
  become: yes
  tasks:
  - name: Installing nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      
  - name: message
    ansible.builtin.debug:
      msg: "Installed Successfully and started enabled"