- name: Getting Variables from other file
  hosts:  web
  vars_files:
  -  vars.yml
  tasks:
  -  name: Sample of other file variables
    ansible.builtin.debug:
      msg: "This is {{Course}}, {{duration}}, by {{mentor}}"